### PR TITLE
chore: add colorful arch pic

### PR DESCRIPTION
**Pull request by TianyuZhang1214**

### CODE REVIEW

**Comment by VWagen1989** [comment]
Is it better to add some icons for these modules shown in the architecture? e.g. We add the following icon to the "Embedded DuckDB". I think it's much straight forward to understand what is in the architecture with icons.
image

**Comment by fanyang01** [comment]
> Is it better to add some icons for these modules shown in the architecture?

Good idea!

**Comment by TianyuZhang1214** [comment]
> Is it better to add some icons for these modules shown in the architecture? e.g. We add the following icon to the "Embedded DuckDB". I think it's much straight forward to understand what is in the architecture with icons. image

Adopted!

**Review by VWagen1989 — APPROVED** [review]
Excellent work! LGTM!

**Pull request merged**
